# Generated by Django 3.2.16 on 2022-11-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_is_admin_user_is_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stuff',
        ),
    ]
