# Generated by Django 3.2.16 on 2022-11-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_user_is_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whetherthis user should be treated as moderator.', verbose_name='admin status'),
        ),
    ]
