# Generated by Django 2.2.16 on 2022-11-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221116_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
