# Generated by Django 2.2.16 on 2022-11-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221116_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Designates whetherthis user should be treated as moderator.', verbose_name='moderator'),
        ),
    ]
