# Generated by Django 3.2.16 on 2022-11-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_category_comment_genre_review_title'),
        ('reviews', '0006_user_is_moderator'),
    ]

    operations = [
    ]
